Init Commit
Kiuh/Pong pull request #2
Opened 2023-10-02 12:53 UTC by d1onaea

2023-10-03 20:27 UTC, Kiuh requested changes

2023-10-03 20:27 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +
Incorrect dependency.
`GameManager` can know something about `Ball` but not vice versa.
Make similar field in `GameManager` and remove this field.

2023-10-03 20:27 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +
And in other scripts too

2023-10-03 20:27 UTC, Kiuh commented on PinkPong/Assets/Scripts/GameManager.cs
> +    }
Don't leave empty methods, it's dead code

2023-10-03 20:27 UTC, Kiuh commented on PinkPong/Assets/Scripts/Paddle.cs
> +    [SerializeField] private GameManager gameManager;
Apply formatter, like it was done in `Ball` script.

2023-10-03 20:27 UTC, Kiuh commented on PinkPong/Assets/Scripts/Paddle.cs
> +    [SerializeField] private GameManager gameManager;
Better apply formatter to all scripts

2023-10-03 20:27 UTC, Kiuh commented on PinkPong/Assets/Scripts/Paddle.cs
> +    }
Try separate this logic in two scripts, one of them will manage only input of paddle and other one only paddle movement.

2023-10-03 20:27 UTC, Kiuh commented on PinkPong/Assets/Scripts/Paddle.cs
> +    }
Better introduce script that will manage all user input.

2023-10-04 17:51 UTC, mertwole requested changes

2023-10-04 17:51 UTC, mertwole commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +    }
```suggestion
    private void Dash(float movement)
    {
        transform.RotateAround(target.position, Vector3.forward * movement, Time.deltaTime * dashSpeed);
    }
```

2023-10-04 18:06 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +        input.IsDoublePressed += Dash;
Don't use events here, just use `Dash` the same way as `Move` - call it from `PaddleInput`

2023-10-04 18:07 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +    [SerializeField] private PaddleInput input;
```suggestion
```

2023-10-04 18:09 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +    private void Dash(float movement)
Assure that dash mechanic is working properly - it should teleport paddle instead of speeding it up

2023-10-04 18:09 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +    private void Dash(float movement)
And, of course, it shouldn't depend on `Time.deltaTime`

2023-10-04 18:10 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +//}
```suggestion
```
Don't leave commented out code in git

2023-10-04 18:11 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +//� �� ��� ��� ������� ��������� ������
:grin:

2023-10-04 18:11 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
Please re-check that formatter is working

2023-10-04 18:29 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +    private void InitialPush()
Change the logics to actually generating normalized direction and the multiplying it to `moveSpeed`

2023-10-04 18:30 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +    private void InitialPush()
Use trigonometry for generating normalized direction

2023-10-04 18:30 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +    [SerializeField] private float maxInitAngle = 0.67f;
It woulde more convinient if this value will be specified in degrees

2023-10-04 18:33 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +    private void ResetBallPosition()
The logics here is different from one discussed

2023-10-04 18:42 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleInput.cs
> +        if (Input.GetButtonUp(inputButton))
```suggestion
        if (Input.GetButtonDown(inputButton))
```

2023-10-04 18:43 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleInput.cs
> +    }
```suggestion
    private bool DoublePressCheck()
    {
         var doublePressed = Time.time - lastPressedTime > delayBetweenPresses;
         lastPressedTime = Time.time;
         return doublePressed;
    }
```

2023-10-04 18:48 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +    public void Move(float movement)
```suggestion
    public void Move(RotationDirection direction)
```

where `RotationDirection` is 
```c#
enum RotationDirection {
    Clockwise,
    CounterClockWise
}
```

2023-10-04 18:49 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +        transform.RotateAround(target.position, new Vector3(0, 0, 1) * movement, Time.deltaTime * speed);
This approach is counter-intuitive, better multiply the third argument to direction. Select multiplier in accordance to the `RotationDirection` enum value by `switch`

2023-10-04 18:50 UTC, Kiuh commented on PinkPong/Assets/Scripts/PaddleMovement.cs
> +        transform.RotateAround(target.position, new Vector3(0, 0, 1) * movement, Time.deltaTime * speed);
```suggestion
        transform.RotateAround(target.position, Vector3.forward * movement, Time.deltaTime * speed);
```

2023-10-04 18:52 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +    [SerializeField] private Rigidbody2D rb2d;
```suggestion
    [SerializeField] private Rigidbody2D rigidbody;
```

2023-10-04 18:53 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +    private readonly float maxStartY = 4f;
`[SerializeField] private ...` approach here

2023-10-04 19:17 UTC, d1onaea commented on PinkPong/Assets/Scripts/Ball.cs
> +    private readonly float maxStartY = 4f;
why? it's not like you need to change the value in the inspector

2023-10-04 19:43 UTC, Kiuh commented on PinkPong/Assets/Scripts/Ball.cs
> +    private readonly float maxStartY = 4f;
because if something changes in environment, you will go to the code to change it.

2023-10-06 19:28 UTC, Kiuh approved these changes

2023-10-06 19:33 UTC, merged